### ISSUE TITLE
Webapp MVP

### ISSUE THREAD

**Issue by AquiGorka** [citrusbyte/universal-wallet#8]
- [ ] Refactor into more "solid features"
  - [x] Sign in 
  - [ ] Wallets
    - [ ] Generate wallet
      - [x] bitcoin
      - [x] ether
      - [ ] ...rest: https://github.com/citrusbyte/universal-wallet/issues/17
    - [x] Import raw wallet
    - [x] Import wallet using WIF: https://github.com/citrusbyte/universal-wallet/issues/16
  - [x] Receive assets (show public address and qr code)
  - [ ] Send assets
    - [x] bitcoin
    - [x] ether
    - [ ] ...rest: https://github.com/citrusbyte/universal-wallet/issues/18
  - [ ] In wallet trading (origin wallet)
    - [x] bitcoin
    - [x] ether
    - [ ] ...rest: https://github.com/citrusbyte/universal-wallet/issues/18
  - [x] Transaction history
  - [x] Custom tokens (send, receive and in wallet trade): https://github.com/citrusbyte/universal-wallet/issues/19
- [ ] Tests
  - [ ] Setup Jest: https://github.com/citrusbyte/universal-wallet/issues/20
  - [ ] Automate transactions with testnet: https://github.com/citrusbyte/universal-wallet/issues/22

**Comment by AquiGorka** [comment]
Closing for documenting purposes for the project.
Follow ups here: #35 and #36
